### ISSUE TITLE
为什么ANYmal的小腿要做成弯的

### ISSUE THREAD

**Issue by guzhaoyuan** [thu-skyworks/Roboseum#3]
1 感觉直的和弯的有一样的驱动效果
2 弯的设计复杂，加工困难
3 电机能转360°，弯直应该都一样能控制

**Comment by Yiping-Steven** [comment]
做成弯的有利于吸收冲击力。如果是直的，那么地面冲击力就直接作用在两个关节上。如果做成弯的，地面冲击力可以产生力矩，通过电机吸收转化大部分冲击力，使得机械结构更加鲁棒、稳定。
