### ISSUE TITLE
机器人传感器里面是不是应该加一个IMU

### ISSUE THREAD

**Issue by Jackey-Huo** [thu-skyworks/Roboseum#7]
IMU很重要的呀，特别是在一些slam算法里面

**Comment by guzhaoyuan** [comment]
不仅可以加IMU，也还可以加霍尔，旋转变压器，编码器等电机角度反馈元件。

**Comment by guzhaoyuan** [comment]
sensors added
@guzhaoyuan@1ca1e8ed84e8a584ffb0650b604c67872e455c75
